# Generated by Django 5.2.9 on 2026-01-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachathlete',
            options={'verbose_name': 'Coach-Athlete link', 'verbose_name_plural': 'Coach-Athlete links'},
        ),
    ]
