# Generated by Django 5.2.9 on 2026-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_coach_join_code_coachjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachathlete',
            name='hidden_from_plans',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
