# Generated by Django 5.2.9 on 2026-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_google_role_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
