# Generated by Django 5.2.9 on 2026-02-07 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('run', 'Run'), ('bike', 'Bike'), ('swim', 'Swim'), ('other', 'Other')], default='run', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('average_hr', models.PositiveIntegerField(blank=True, null=True)),
                ('max_hr', models.PositiveIntegerField(blank=True, null=True)),
                ('is_interval_session', models.BooleanField(default=False)),
                ('athlete_note', models.TextField(blank=True)),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('time_s', models.PositiveIntegerField(default=0)),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('avg_hr', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='activities.activity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
