# Generated by Django 5.2.9 on 2026-02-07 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='average_hr',
            new_name='avg_pace_s_per_km',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='max_hr',
            new_name='duration_s',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='start_time',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='athlete_note',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_interval_session',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='source_file_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_hr',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sport',
            field=models.CharField(choices=[('RUN', 'Run'), ('BIKE', 'Bike'), ('SWIM', 'Swim'), ('OTHER', 'Other')], default='RUN', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('FIT', 'FIT'), ('GPX', 'GPX'), ('TCX', 'TCX'), ('OTHER', 'OTHER')], default='FIT', max_length=10)),
                ('file', models.FileField(upload_to='activity_files/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_pace_s_per_km', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='activities.activity')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('activity', 'index')},
            },
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
    ]
