# Generated by Django 5.2.9 on 2026-02-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_average_hr_activity_avg_pace_s_per_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('EASY', 'Easy'), ('WORKOUT', 'Workout')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='activityinterval',
            name='trigger',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('DISTANCE', 'Distance (auto-lap)'), ('MANUAL', 'Manual (button)'), ('TIME', 'Time'), ('SESSION', 'Session')], default='UNKNOWN', max_length=20),
        ),
    ]
