# Generated by Django 5.2.9 on 2026-02-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_workout_type_activityinterval_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='workout_type',
        ),
        migrations.RemoveField(
            model_name='activityinterval',
            name='trigger',
        ),
    ]
