# Generated by Django 5.2.9 on 2026-02-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_activity_workout_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityinterval',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='activityinterval',
            constraint=models.UniqueConstraint(fields=('activity', 'index'), name='uniq_activity_interval_index'),
        ),
    ]
