# Generated by Django 5.2.9 on 2026-02-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activityinterval_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activityinterval',
            name='uniq_activity_interval_index',
        ),
        migrations.AddField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('EASY', 'Easy'), ('WORKOUT', 'Workout')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='activityinterval',
            unique_together={('activity', 'index')},
        ),
    ]
