# Generated by Django 5.2.9 on 2026-02-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_remove_activityinterval_uniq_activity_interval_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('RUN', 'Run'), ('WORKOUT', 'Workout')], default='UNKNOWN', max_length=20),
        ),
    ]
