# Generated by Django 5.2.9 on 2026-02-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activity_workout_type'),
        ('training', '0003_alter_plannedtraining_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='planned_training',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='training.plannedtraining'),
        ),
        migrations.AddField(
            model_name='activityfile',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(choices=[('RUN', 'Run (easy)'), ('WORKOUT', 'Workout'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='activityfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='activity_files/%Y/%m/'),
        ),
    ]
