# Generated by Django 5.2.9 on 2026-02-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_planned_training_activityfile_raw_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_hr',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityinterval',
            name='max_hr',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_pace_s_per_km', models.PositiveIntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='activities.activity')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('activity', 'index')},
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cadence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='activities.activity')),
            ],
            options={
                'ordering': ['ts'],
                'indexes': [models.Index(fields=['activity', 'ts'], name='activities__activit_87ed90_idx')],
            },
        ),
    ]
