# Generated by Django 5.2.9 on 2026-02-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_max_hr_activityinterval_max_hr_activitylap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityrecord',
            name='activity',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-started_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='max_hr',
        ),
        migrations.RemoveField(
            model_name='activityfile',
            name='raw_json',
        ),
        migrations.RemoveField(
            model_name='activityinterval',
            name='max_hr',
        ),
        migrations.AlterField(
            model_name='activityfile',
            name='file',
            field=models.FileField(upload_to='activity_files/%Y/%m/'),
        ),
        migrations.DeleteModel(
            name='ActivityLap',
        ),
        migrations.DeleteModel(
            name='ActivityRecord',
        ),
    ]
