# Generated by Django 5.2.9 on 2026-02-13 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_remove_activityrecord_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='activity_files/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='ActivitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_s', models.PositiveIntegerField()),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speed_m_s', models.FloatField(blank=True, null=True)),
                ('cadence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('power', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='activities.activity')),
            ],
            options={
                'ordering': ['t_s'],
                'indexes': [models.Index(fields=['activity', 't_s'], name='activities__activit_6318ca_idx')],
            },
        ),
    ]
