# Generated by Django 5.2.9 on 2026-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_activityfile_file_activitysample'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_hr',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityinterval',
            name='max_hr',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
