# Generated by Django 5.2.9 on 2026-01-25 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Month',
                'verbose_name_plural': 'Training Months',
                'ordering': ['-year', '-month'],
                'unique_together': {('athlete', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TrainingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_index', models.PositiveIntegerField()),
                ('training_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='training.trainingmonth')),
            ],
            options={
                'verbose_name': 'Training Week',
                'verbose_name_plural': 'Training Weeks',
                'ordering': ['week_index'],
                'unique_together': {('training_month', 'week_index')},
            },
        ),
        migrations.CreateModel(
            name='PlannedTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('planned_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order_in_day', models.PositiveIntegerField(default=1)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_trainings', to='training.trainingweek')),
            ],
            options={
                'verbose_name': 'Planned training',
                'verbose_name_plural': 'Planned trainings',
                'ordering': ('week__week_index', 'day_label', 'order_in_day'),
            },
        ),
    ]
