# Generated by Django 5.2.9 on 2026-02-07 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_average_hr_activity_avg_pace_s_per_km_and_more'),
        ('training', '0002_completedtraining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedtraining',
            options={'ordering': ('week__week_index', 'date', 'order_in_day'), 'verbose_name': 'Planned training', 'verbose_name_plural': 'Planned trainings'},
        ),
        migrations.AddField(
            model_name='completedtraining',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_training', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='plannedtraining',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
